#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fastapi"
name = "my_FastAPI_app"
description.en = "Custom Web app to run a FastAPI program written in Python"
description.fr = "Une application web personnalisée pour faire tourner une application FastAPI écrite en Python"

version = "1.0~ynh1"

maintainers = ["leonarf"]

[upstream]
license = "GPL-3.0-or-later"
code = "https://github.com/leonarf/FastAPI_ynh"

[integration]
yunohost = ">= 11.2.5"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "350M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/api"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    ask.en = "Password that you will need to upload your code on YunoHost"
    ask.fr = "Le mot de passe que vous utiliserez pour téléverser votre code sur Yunohost"
    type = "password"

[resources]
    [resources.system_user]
    allow_sftp = true
    allow_ssh = false
    home = "/home/yunohost.app/__APP__"
    # This will provision/deprovision a unix system user

    [resources.install_dir]

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir
    dir = "/home/yunohost.app/__APP__"

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = "python3-dev, python3-pip, python3-venv"
